<?php
	/*
	* Script reads new task information from input parameters and puts data 
	* in database for current category. (tid is generated by DB)
	*
	* input parameters:
	* 	
	* name [string], 
	* start[string], 
	* end[string], 
	* cid[int],	
	* priority[int], 
	* reminder[string] (obsolete),
	* reminderSMS[int],
	* reminderEmail[int],
	* repeat[string], 
	* repeatEnd[string]
	*
	* output format:
	* {"response" : true} 
	*/
	/* insert global variables*/
	include('../php/include/sessionAjax.php');
		
	function checkParameters() {
		$para = isset($_POST['name']) && isset($_POST['start']) && isset($_POST['end']) && isset($_POST['cid'])&&
		        isset($_POST['priority']) && isset($_POST['reminderSMS']) && isset($_POST['reminderEmail']) &&
			    isset($_POST['repeatEnd']) && isset($_POST['repeat']);
		//echo ($_POST['repeatEnd']);
		return $para;
	}
	
	if($session->logged_in) {
		$posts = array();
		if(DB_CONNECT && checkParameters()) {
			if(empty($_POST['name'])) {
				$posts = array ("response" => false);
				header('Content-type: application/json');
				echo json_encode($posts);
				exit();
			}
			$query = "SELECT ID_user ".
					 "FROM ".TBL_USERS." ".
					 "WHERE username='$session->username'";
					 
			$result = $database->query($query);
			$dbarray = mysql_fetch_array($result);
			$user_id = (int)$dbarray['ID_user'];
			
			$start_date = ($_POST['start'] == " ") ? date('Y-m-d H:i:s') : convertDateAndTimeUItoDB($_POST['start']);
			$due_date = ($_POST['end'] == " ") ? date('Y-m-d H:i:s') : convertDateAndTimeUItoDB($_POST['end']);
			$repeat_end = empty($_POST['repeatEnd']) ? date('Y-m-d H:i:s') : convertDateUItoDB($_POST['repeatEnd']);
			$repeat_end = empty($_POST['repeatEnd']) ? "0000-00-00 00:00:00" : convertDateUItoDB($_POST['repeatEnd']);
				
			$repeat = repeatUItoDB($_POST['repeat']);
			$reminderSMS = reminderUItoDB($_POST['reminderSMS']);
			$reminderEmail = reminderUItoDB($_POST['reminderEmail']);
			 //echo "aaaa";
			 //print_r($repeat);
			 //echo "aaaa";
			$query = "INSERT INTO ".TBL_TASK." (ID_category, ID_user, title, description, estimated_time, start_date, due_date, repeat_time, repeat_ends, priority, reminder_email, reminder_sms, acknowledge, remindered_email, remindered_sms) ".
					 "VALUES (".(int)$_POST['cid'].", ".$user_id.", '".$_POST['name']."', '', 0, '".$start_date."', '".$due_date."', ".$repeat.", '".$repeat_end."', ".$_POST['priority'].", ".$reminderEmail.", ".$reminderSMS.", 0, 0, 0)";
			
			//echo $query;
			$result =  $database->query($query);
			$res1 = $result; 
			$task_id = mysql_insert_id();
			
			if ($repeat != "0") {
				$query = "INSERT INTO ".TBL_PERTASK." (ID_task, generated_ID_task) VALUES (" . $task_id .", ". $task_id . ")";
				$result = $database->query($query);
				$res2 = $result;
				
				// response
				$posts = array ("response" => ($res1 == true && $res2 == true));
			} else {
				// response
				$posts = array ("response" => ($res1 == true));
			}
			
			header('Content-type: application/json');
						
			echo json_encode($posts);
		} else {
			header($_SERVER['SERVER_PROTOCOL'] . ' 503 Service Unavailable', true, 503);
		}
	} else {
		/* not logged in. */
		header($_SERVER['SERVER_PROTOCOL'] . ' 500 Internal Server Error', true, 500);
	}
 
?>